/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ReactLazyImport = createFileRoute('/react')()
const JsLazyImport = createFileRoute('/js')()

// Create/Update Routes

const ReactLazyRoute = ReactLazyImport.update({
  path: '/react',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/react.lazy').then((d) => d.Route))

const JsLazyRoute = JsLazyImport.update({
  path: '/js',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/js.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/js': {
      preLoaderRoute: typeof JsLazyImport
      parentRoute: typeof rootRoute
    }
    '/react': {
      preLoaderRoute: typeof ReactLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  JsLazyRoute,
  ReactLazyRoute,
])

/* prettier-ignore-end */
